### ISSUE TITLE
OS X compilation fails on zeroconf on OS X 10.11

### ISSUE THREAD

**Issue by stephanemagnenat** [aseba-community/aseba#566]
The compliation fails on our build farm due to recent zeroconf commit:

```
[  1%] Building CXX object common/CMakeFiles/asebacommon.dir/zeroconf/zeroconf.cpp.o
/Users/administrator/jenkins/workspace/aseba.osx/source/aseba/common/zeroconf/zeroconf.cpp:126:10: warning: implicit conversion of NULL constant to 'DNSServiceFlags' (aka 'unsigned int') [-Wnull-conversion]
                                                                 NULL,
                                                                 ^~~~
                                                                 0
/Users/administrator/jenkins/workspace/aseba.osx/source/aseba/common/zeroconf/zeroconf.cpp:221:23: error: no viable overloaded '='
                                target.properties = { {"name",string(name)}, {"domain",string(domain)} };
                                ~~~~~~~~~~~~~~~~~ ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/c++/4.2.1/bits/stl_map.h:226:7: note: candidate function not viable: cannot convert initializer list argument to 'const std::map<std::basic_string<char>, std::basic_string<char>, std::less<std::basic_string<char> >, std::allocator<std::pair<const std::basic_string<char>, std::basic_string<char> > > >'
      operator=(const map& __x)
      ^
1 warning and 1 error generated.
make[2]: *** [common/CMakeFiles/asebacommon.dir/zeroconf/zeroconf.cpp.o] Error 1
make[1]: *** [common/CMakeFiles/asebacommon.dir/all] Error 2
make: *** [all] Error 2
Build step 'Execute shell' marked build as failure
Archiving artifacts
Warning: you have no plugins providing access control for builds, so falling back to legacy behavior of permitting any downstream builds to be triggered
Finished: FAILURE
```

**Comment by stephanemagnenat** [comment]
Master branch works on macOS 10.12, closing.
